name: Package Installation

on: [push]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Package Setup
      run: |
        pip install setuptools
        ./ci/setup.sh
